### PR TITLE
Cmake filter mac dotfiles

### PR DESCRIPTION
**Pull request by ccreutzi**
- [X] Accept to license the library and tools code under the terms
  of the [LGPL 2.0](https://spdx.org/licenses/LGPL-2.0-or-later.html) or later
- [X] Accept to license the library and tools code under the terms
  of the [MPL 2.0](https://spdx.org/licenses/MPL-2.0)
- [X] Accept to license the test code under the terms
  of the [MIT-0](https://spdx.org/licenses/MIT-0.html)
- [X] Read [contributions](https://github.com/podofo/podofo#contributions) guidelines
- [X] Checked coding [style](https://github.com/podofo/podofo/blob/master/CODING-STYLE.md)
- [X] The commits sequence is clean without work in progress/bugged revisions and merge commits. In doubt, [squash](https://github.com/podofo/podofo/wiki/Squash-git-history-guide) the commits and/or rebase master

### CODE REVIEW

**Comment by ceztko** [comment]
Ok, I thought about it a little bit more and because this is fixing a problem that in a better world we shouldn't care about, I would prefer a better glob expression than filtering all our globs in a separate step. What do you think about this patch? It applies to current master HEAD (which had your first patch already). The idea is not including files that starts with a dot (which fortunately makes sense in all the affected globs).

[better-globbing-expressions.diff.txt](https://github.com/user-attachments/files/16026504/better-globbing-expressions.diff.txt)

**Comment by ceztko** [comment]
Please tell me if the patch works for you.

**Comment by ccreutzi** [comment]
That alternative sure does look reasonable, yes. If anyone ever does create `src/podofo/.cpp`, that will also be excluded, but I do not see how that is a bad thing.

**Comment by ceztko** [comment]
I committed the patch in https://github.com/podofo/podofo/commit/4d5e119d0cab1285dc2e48c290fc033c707d41c4. Let me know if you have other issues.

**Pull request closed without merging**
